name = "dmem"
main = "./dist/index.js"
#https://developers.cloudflare.com/workers/platform/compatibility-dates/#change-history
compatibility_date = "2022-11-30"
account_id = "TODO"

kv_namespaces = [
    { binding = "DMEM_KV", id = "TODO" }
]

# scheduled worker only, so no worker dev deployment is needed
workers_dev = false

send_metrics = false

[triggers]
#Every five (5) minutes
crons = [ "*/5 * * * *" ]
